### ISSUE TITLE
"Initialised a molecule from an xyz file with an odd number of electrons but had an even charge and 2S + 1 = 1. Impossible!"

### ISSUE THREAD

**Issue by SixuanMi** [chimie-paristech-CTM/TS-tools#9]
Hi,

I have tried to run the following reaction when finding TS in xTB level:
[C:1]#[C:2][H:3].[C:4]1([H:9])=[C:5]([H:10])[C:6]([H:11])([H:12])[C:7]([H:13])=[C:8]1[H:14]>>[C:1](#[C:2][H:3])[H:11].[C:4]1([H:9])=[C:5]([H:10])[C:6]([H:12])=[C:7]([H:13])[C:8]1[H:14]
But it encountered a problem "Initialised a molecule from an xyz file with an odd number of electrons but had an even charge and 2S + 1 = 1. Impossible!".
I have notice there is a code to detect multiplicity in TS-tools and the code can detect the reactant as charge=0, multi=2 correctly. I do not know what's wrong. Could you help me? Thanks a lot!

Best wishes,
Mi

**Comment by tstuyver** [comment]
Hi Mi, 

How did you generate this reaction SMILES? Because there are several errors in there. First of all, your reaction needs to be balanced, so every atom on the reactant side also needs to be present on the product side. This is not the case in your example (atoms 2 and 3 are present in the reactants but not in the products, and for atom 11 it is the reverse). Apart from that, you are missing several hydrogens, and the brackets around the atom symbols and map numbers are also missing here and there.

If you provide a correct reaction SMILES, I can figure out if there is a bug in the code.

Kind regards,
Thijs

**Comment by SixuanMi** [comment]
Hi Thijs, 

I generated the reaction SMILES form atom-mapped xyz file, using obabel and RDKit. Sorry for my mistake to paste the wrong reaction SMILES. It should be:
[C:1]#[C:2][H:3].[C:4]1([H:9])=[C:5]([H:10])[C:6]([H:11])([H:12])[C:7]([H:13])=[C:8]1[H:14]>>[C:1](#[C:2][H:3])[H:11].[C:4]1([H:9])=[C:5]([H:10])[C:6]([H:12])=[C:7]([H:13])[C:8]1[H:14]

It is a H-transfer reaction. [H:11] transfered from cyclopentadiene to ethynyl radical. I wrote this in test.rsmi file and ran command below.
`python run_scripts/run_ts_searcher.py --input-file test.rsmi --xtb-external-path xtb_external_script/xtb_external.py`

The results were below.
1 reactions to process...
Initialised a molecule from an xyz file with  an odd number of electrons but had an even charge and 2S + 1 = 1. Impossible!
Successful reactions: []
Number of successful reactions: 0
Time taken: 1.4479701519012451

Best,
Mi

**Comment by tstuyver** [comment]
Hi Mi,

Sorry for the delay; there was a bug and it took me some time before I was able to fix it (you may need to run the code twice, because I think that sometimes the radical abstracts the "wrong" hydrogen, causing one of the validation checks to result in an error -- I should fix this very specific issue for radicals at some point, but I typically obtain the TSs either on first or second try in the current version).

Kind regards,
Thijs

**Comment by SixuanMi** [comment]
I see, thank you very much. :-)
